FROM node:24-bookworm-slim AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG VITE_JELLYFIN_URL
ARG VITE_IMMICH_URL
ARG VITE_AUDIOBOOKSHELF_URL
ARG VITE_SEERR_URL
ARG VITE_SONARR_URL
ARG VITE_RADARR_URL
ARG VITE_PROWLARR_URL
ARG VITE_DELUGE_URL

ENV VITE_JELLYFIN_URL=$VITE_JELLYFIN_URL
ENV VITE_IMMICH_URL=$VITE_IMMICH_URL
ENV VITE_AUDIOBOOKSHELF_URL=$VITE_AUDIOBOOKSHELF_URL
ENV VITE_SEERR_URL=$VITE_SEERR_URL
ENV VITE_SONARR_URL=$VITE_SONARR_URL
ENV VITE_RADARR_URL=$VITE_RADARR_URL
ENV VITE_PROWLARR_URL=$VITE_PROWLARR_URL
ENV VITE_DELUGE_URL=$VITE_DELUGE_URL

RUN npm run build


FROM nginx:alpine AS production

COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80