import { serviceUrls } from "../../config/serviceUrls";
import type { Service } from "./service.types";

export const serviceCatalog: Service[] = [
  {
    id: "jellyfin",
    name: "Jellyfin",
    description: "Watch movies and TV shows",
    category: "media",
    access: "family",
    icon: "/icons/services/jellyfin.svg",
    href: serviceUrls.jellyfin,
  },
  {
    id: "immich",
    name: "Immich",
    description: "Browse and back up photos and videos",
    category: "photos",
    access: "family",
    icon: "/icons/services/immich.svg",
    href: serviceUrls.immich,
  },
  {
    id: "audiobookshelf",
    name: "Audiobookshelf",
    description: "Browse audiobooks and books",
    category: "media",
    access: "family",
    icon: "/icons/services/audiobookshelf.svg",
    href: serviceUrls.audiobookshelf,
  },
  {
    id: "seerr",
    name: "Seerr",
    description: "Request movies and TV shows",
    category: "requests",
    access: "family",
    icon: "/icons/services/seerr.svg",
    href: serviceUrls.seerr,
  },
  {
    id: "sonarr",
    name: "Sonarr",
    description: "Manage TV shows",
    category: "admin",
    access: "admin",
    icon: "/icons/services/sonarr.svg",
    href: serviceUrls.sonarr,
  },
  {
    id: "radarr",
    name: "Radarr",
    description: "Manage movies",
    category: "admin",
    access: "admin",
    icon: "/icons/services/radarr.svg",
    href: serviceUrls.radarr,
  },
  {
    id: "prowlarr",
    name: "Prowlarr",
    description: "Manage indexers",
    category: "admin",
    access: "admin",
    icon: "/icons/services/prowlarr.svg",
    href: serviceUrls.prowlarr,
  },
  {
    id: "deluge",
    name: "Deluge",
    description: "Manage downloads",
    category: "admin",
    access: "admin",
    icon: "/icons/services/deluge.svg",
    href: serviceUrls.deluge,
  },
];
