import type { Service } from "./service.types";

export const serviceCatalog: Service[] = [
  {
    id: "jellyfin",
    name: "Jellyfin",
    description: "Watch movies and TV shows",
    category: "media",
    access: "family",
    icon: "J",
  },
  {
    id: "immich",
    name: "Immich",
    description: "Browse and back up photos and videos",
    category: "photos",
    access: "family",
    icon: "I",
  },
  {
    id: "audiobookshelf",
    name: "Audiobookshelf",
    description: "Browse audiobooks and books",
    category: "media",
    access: "family",
    icon: "A",
  },
  {
    id: "seerr",
    name: "Seerr",
    description: "Request movies and TV shows",
    category: "requests",
    access: "family",
    icon: "S",
  },
  {
    id: "sonarr",
    name: "Sonarr",
    description: "Manage TV shows",
    category: "admin",
    access: "admin",
    icon: "S",
  },
  {
    id: "radarr",
    name: "Radarr",
    description: "Manage movies",
    category: "admin",
    access: "admin",
    icon: "R",
  },
  {
    id: "prowlarr",
    name: "Prowlarr",
    description: "Manage indexers",
    category: "admin",
    access: "admin",
    icon: "P",
  },
  {
    id: "deluge",
    name: "Deluge",
    description: "Manage downloads",
    category: "admin",
    access: "admin",
    icon: "D",
  },
];
